repositories:
  - name: fswatcher
    url: https://github.com/fredjeck/fswatcher.git
    user_name: user
    password: pwd
    refresh_interval: 12
  - name: repo2
    url: http://test
    user_name: user
    password: pwd
    refresh_interval: 12
