name: "Test Config Server"
encryptionKey: "vpvY35wo3LFl@76bXqgz3HOb13TN&oE8jqvMbkXMD#q4cv0hvQ"
network:
  host: 127.0.0.1
  port: 8080
repositories:
  - name: fswatcher
    url: https://github.com/fredjeck/fswatcher.git
    user_name: user
    password: pwd
    refresh_interval: 120000
    credentials:
      - user_name: admin
        password: admin
  - name: repo2
    url: http://test
    user_name: user
    password: pwd
    refresh_interval: 120000
    credentials:
      - user_name: admin
        password: admin
